package ui;

import javax.swing.*;
import javax.swing.border.TitledBorder;
import java.awt.*;
import java.awt.event.*;

public class ProgramFrame extends JFrame {

	private JPanel parentPanel;
	private JPanel cardPanel;
	private JPanel tabsPanel;
	private JButton yourAccountButton;
	private JButton sendPackageButton;
	private JButton trackPackageButton;
	private JButton yourPackagesButton;
	private JPanel yourPackagesPanel;
	private JPanel trackPackagePanel;
	private JPanel sendPackagePanel;
	private JPanel spPanel;
	private JLabel typeLabel;
	private JLabel dimensionsLabel;
	private JLabel weightLabel;
	private JTextField weightField;
	private JTextField dimensionsField;
	private JComboBox typeComboBox;
	private JLabel titleLabel;
	private JLabel messageLabel;
	private JButton printButton;
	private JPanel tpPanel;
	private JPanel yourAccountPanel;
	private JPanel yaPanel;
	private JPanel ypPanel;
	private JPanel packageListPanel;
	private JLabel yaTitleLabel;
	private JLabel ypTitleLabel;
	private JLabel ypMessageLabel;
	private JLabel firstNLabel;
	private JLabel fLabel;
	private JLabel lLabel;
	private JLabel pLabel;
	private JLabel phoneLabel;
	private JLabel lastNLabel;
	private JLabel emailLabel;
	private JLabel eLabel;
	private JLabel addressLabel;
	private JLabel aLabel;
	private JLabel tpTitleLabel;
	private JTextField textField1;

	public ProgramFrame() {

		setContentPane(parentPanel);
		setLocationRelativeTo(null);
		//setPreferredSize(new Dimension(800, 900));
		setResizable(false);
		pack();
		setVisible(true);

		setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);

		CardLayout cardLayout = (CardLayout) (cardPanel.getLayout());


		addWindowListener(new WindowAdapter() {
			public void windowClosing(WindowEvent e) {
				System.exit(0);
			}
		});

		// YOUR PACKAGES BUTTON LISTENER
		yourPackagesButton.addActionListener(new ActionListener() {
			@Override
			public void actionPerformed(ActionEvent actionEvent) {
				cardLayout.show(cardPanel, "yourPackagesCard");
			}
		});

		// TRACK PACKAGE BUTTON LISTENER
		trackPackageButton.addActionListener(new ActionListener() {
			@Override
			public void actionPerformed(ActionEvent actionEvent) {
				cardLayout.show(cardPanel, "trackPackageCard");
			}
		});


		// SEND PACKAGE BUTTON LISTENER
		sendPackageButton.addActionListener(new ActionListener() {
			@Override
			public void actionPerformed(ActionEvent actionEvent) {
				cardLayout.show(cardPanel, "sendPackageCard");
			}
		});

		// YOUR ACCOUNT BUTTON LISTENER
		yourAccountButton.addActionListener(new ActionListener() {
			@Override
			public void actionPerformed(ActionEvent actionEvent) {
				cardLayout.show(cardPanel, "yourAccountCard");
			}
		});

	}


	{
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
		$$$setupUI$$$();
	}

	/**
	 * Method generated by IntelliJ IDEA GUI Designer
	 * >>> IMPORTANT!! <<<
	 * DO NOT edit this method OR call it in your code!
	 *
	 * @noinspection ALL
	 */
	private void $$$setupUI$$$() {
		parentPanel = new JPanel();
		parentPanel.setLayout(new BorderLayout(0, 0));
		tabsPanel = new JPanel();
		tabsPanel.setLayout(new GridBagLayout());
		parentPanel.add(tabsPanel, BorderLayout.WEST);
		yourAccountButton = new JButton();
		yourAccountButton.setBorderPainted(false);
		yourAccountButton.setContentAreaFilled(false);
		yourAccountButton.setIcon(new ImageIcon(getClass().getResource("/icons/user-menu-female-96.png")));
		yourAccountButton.setText("Your Account");
		GridBagConstraints gbc;
		gbc = new GridBagConstraints();
		gbc.gridx = 0;
		gbc.gridy = 3;
		gbc.fill = GridBagConstraints.HORIZONTAL;
		gbc.insets = new Insets(200, 0, 50, 0);
		tabsPanel.add(yourAccountButton, gbc);
		sendPackageButton = new JButton();
		sendPackageButton.setBorderPainted(false);
		sendPackageButton.setContentAreaFilled(false);
		sendPackageButton.setIcon(new ImageIcon(getClass().getResource("/icons/move-stock-96.png")));
		sendPackageButton.setText("Send Package");
		gbc = new GridBagConstraints();
		gbc.gridx = 0;
		gbc.gridy = 2;
		gbc.fill = GridBagConstraints.HORIZONTAL;
		gbc.insets = new Insets(50, 0, 50, 0);
		tabsPanel.add(sendPackageButton, gbc);
		trackPackageButton = new JButton();
		trackPackageButton.setBorderPainted(false);
		trackPackageButton.setContentAreaFilled(false);
		trackPackageButton.setIcon(new ImageIcon(getClass().getResource("/icons/handcart-96.png")));
		trackPackageButton.setText("Track Package");
		gbc = new GridBagConstraints();
		gbc.gridx = 0;
		gbc.gridy = 1;
		gbc.fill = GridBagConstraints.HORIZONTAL;
		gbc.insets = new Insets(50, 0, 50, 0);
		tabsPanel.add(trackPackageButton, gbc);
		yourPackagesButton = new JButton();
		yourPackagesButton.setBorderPainted(false);
		yourPackagesButton.setContentAreaFilled(false);
		yourPackagesButton.setIcon(new ImageIcon(getClass().getResource("/icons/delivered-box-96.png")));
		yourPackagesButton.setOpaque(false);
		yourPackagesButton.setText("Your Packages");
		gbc = new GridBagConstraints();
		gbc.gridx = 0;
		gbc.gridy = 0;
		gbc.fill = GridBagConstraints.HORIZONTAL;
		gbc.insets = new Insets(50, 0, 50, 0);
		tabsPanel.add(yourPackagesButton, gbc);
		cardPanel = new JPanel();
		cardPanel.setLayout(new CardLayout(0, 0));
		parentPanel.add(cardPanel, BorderLayout.CENTER);
		yourPackagesPanel = new JPanel();
		yourPackagesPanel.setLayout(new CardLayout(0, 0));
		cardPanel.add(yourPackagesPanel, "yourPackagesCard");
		ypPanel = new JPanel();
		ypPanel.setLayout(new GridBagLayout());
		yourPackagesPanel.add(ypPanel, "yourPackagesCard");
		ypTitleLabel = new JLabel();
		ypTitleLabel.setText("VIEWING YOUR PACKAGES");
		gbc = new GridBagConstraints();
		gbc.gridx = 1;
		gbc.gridy = 1;
		ypPanel.add(ypTitleLabel, gbc);
		final JPanel spacer1 = new JPanel();
		gbc = new GridBagConstraints();
		gbc.gridx = 1;
		gbc.gridy = 6;
		gbc.fill = GridBagConstraints.VERTICAL;
		gbc.insets = new Insets(20, 0, 200, 0);
		ypPanel.add(spacer1, gbc);
		ypMessageLabel = new JLabel();
		ypMessageLabel.setText("These are known packages related to you: ");
		gbc = new GridBagConstraints();
		gbc.gridx = 0;
		gbc.gridy = 3;
		gbc.gridwidth = 2;
		gbc.anchor = GridBagConstraints.WEST;
		ypPanel.add(ypMessageLabel, gbc);
		final JPanel spacer2 = new JPanel();
		gbc = new GridBagConstraints();
		gbc.gridx = 1;
		gbc.gridy = 2;
		gbc.fill = GridBagConstraints.VERTICAL;
		gbc.insets = new Insets(15, 0, 15, 0);
		ypPanel.add(spacer2, gbc);
		final JPanel spacer3 = new JPanel();
		gbc = new GridBagConstraints();
		gbc.gridx = 1;
		gbc.gridy = 0;
		gbc.fill = GridBagConstraints.VERTICAL;
		gbc.insets = new Insets(20, 0, 0, 0);
		ypPanel.add(spacer3, gbc);
		final JPanel spacer4 = new JPanel();
		gbc = new GridBagConstraints();
		gbc.gridx = 1;
		gbc.gridy = 4;
		gbc.fill = GridBagConstraints.VERTICAL;
		gbc.insets = new Insets(20, 0, 20, 0);
		ypPanel.add(spacer4, gbc);
		packageListPanel = new JPanel();
		packageListPanel.setLayout(new GridBagLayout());
		gbc = new GridBagConstraints();
		gbc.gridx = 1;
		gbc.gridy = 5;
		gbc.fill = GridBagConstraints.BOTH;
		gbc.ipady = 50;
		gbc.insets = new Insets(100, 0, 100, 0);
		ypPanel.add(packageListPanel, gbc);
		packageListPanel.setBorder(BorderFactory.createTitledBorder(BorderFactory.createLineBorder(Color.black), null, TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, null, null));
		trackPackagePanel = new JPanel();
		trackPackagePanel.setLayout(new CardLayout(0, 0));
		cardPanel.add(trackPackagePanel, "trackPackageCard");
		tpPanel = new JPanel();
		tpPanel.setLayout(new GridBagLayout());
		trackPackagePanel.add(tpPanel, "trackPackageCard");
		tpTitleLabel = new JLabel();
		tpTitleLabel.setText("ENTER A PACKAGE TO TRACK");
		gbc = new GridBagConstraints();
		gbc.gridx = 0;
		gbc.gridy = 0;
		gbc.gridwidth = 2;
		gbc.anchor = GridBagConstraints.WEST;
		tpPanel.add(tpTitleLabel, gbc);
		final JPanel spacer5 = new JPanel();
		gbc = new GridBagConstraints();
		gbc.gridx = 0;
		gbc.gridy = 1;
		gbc.gridwidth = 2;
		gbc.fill = GridBagConstraints.VERTICAL;
		tpPanel.add(spacer5, gbc);
		final JLabel label1 = new JLabel();
		label1.setText("Tracking Number:");
		gbc = new GridBagConstraints();
		gbc.gridx = 0;
		gbc.gridy = 2;
		gbc.anchor = GridBagConstraints.WEST;
		gbc.insets = new Insets(0, 0, 0, 50);
		tpPanel.add(label1, gbc);
		textField1 = new JTextField();
		gbc = new GridBagConstraints();
		gbc.gridx = 1;
		gbc.gridy = 2;
		gbc.anchor = GridBagConstraints.WEST;
		gbc.fill = GridBagConstraints.HORIZONTAL;
		gbc.ipadx = 150;
		tpPanel.add(textField1, gbc);
		sendPackagePanel = new JPanel();
		sendPackagePanel.setLayout(new CardLayout(0, 0));
		sendPackagePanel.setAlignmentX(0.5f);
		sendPackagePanel.setAutoscrolls(false);
		sendPackagePanel.setOpaque(true);
		cardPanel.add(sendPackagePanel, "sendPackageCard");
		spPanel = new JPanel();
		spPanel.setLayout(new GridBagLayout());
		sendPackagePanel.add(spPanel, "sendPackageCard");
		typeLabel = new JLabel();
		typeLabel.setText("Package Type:");
		gbc = new GridBagConstraints();
		gbc.gridx = 1;
		gbc.gridy = 5;
		gbc.anchor = GridBagConstraints.WEST;
		spPanel.add(typeLabel, gbc);
		dimensionsLabel = new JLabel();
		dimensionsLabel.setText("Dimensions:");
		gbc = new GridBagConstraints();
		gbc.gridx = 1;
		gbc.gridy = 7;
		gbc.anchor = GridBagConstraints.WEST;
		spPanel.add(dimensionsLabel, gbc);
		weightLabel = new JLabel();
		weightLabel.setText("Weight:");
		gbc = new GridBagConstraints();
		gbc.gridx = 1;
		gbc.gridy = 9;
		gbc.anchor = GridBagConstraints.WEST;
		spPanel.add(weightLabel, gbc);
		weightField = new JTextField();
		gbc = new GridBagConstraints();
		gbc.gridx = 3;
		gbc.gridy = 9;
		gbc.anchor = GridBagConstraints.WEST;
		gbc.fill = GridBagConstraints.HORIZONTAL;
		spPanel.add(weightField, gbc);
		dimensionsField = new JTextField();
		gbc = new GridBagConstraints();
		gbc.gridx = 3;
		gbc.gridy = 7;
		gbc.anchor = GridBagConstraints.WEST;
		gbc.fill = GridBagConstraints.HORIZONTAL;
		spPanel.add(dimensionsField, gbc);
		typeComboBox = new JComboBox();
		gbc = new GridBagConstraints();
		gbc.gridx = 3;
		gbc.gridy = 5;
		gbc.anchor = GridBagConstraints.WEST;
		gbc.fill = GridBagConstraints.HORIZONTAL;
		gbc.ipadx = 200;
		spPanel.add(typeComboBox, gbc);
		titleLabel = new JLabel();
		titleLabel.setText("SENDING A PACKAGE");
		gbc = new GridBagConstraints();
		gbc.gridx = 1;
		gbc.gridy = 1;
		gbc.gridwidth = 3;
		spPanel.add(titleLabel, gbc);
		final JPanel spacer6 = new JPanel();
		gbc = new GridBagConstraints();
		gbc.gridx = 1;
		gbc.gridy = 6;
		gbc.gridwidth = 3;
		gbc.fill = GridBagConstraints.VERTICAL;
		gbc.insets = new Insets(20, 0, 20, 0);
		spPanel.add(spacer6, gbc);
		final JPanel spacer7 = new JPanel();
		gbc = new GridBagConstraints();
		gbc.gridx = 1;
		gbc.gridy = 8;
		gbc.gridwidth = 3;
		gbc.fill = GridBagConstraints.VERTICAL;
		gbc.insets = new Insets(20, 0, 20, 0);
		spPanel.add(spacer7, gbc);
		final JPanel spacer8 = new JPanel();
		gbc = new GridBagConstraints();
		gbc.gridx = 1;
		gbc.gridy = 10;
		gbc.gridwidth = 3;
		gbc.fill = GridBagConstraints.VERTICAL;
		gbc.insets = new Insets(20, 0, 200, 0);
		spPanel.add(spacer8, gbc);
		final JPanel spacer9 = new JPanel();
		gbc = new GridBagConstraints();
		gbc.gridx = 1;
		gbc.gridy = 4;
		gbc.gridwidth = 3;
		gbc.fill = GridBagConstraints.VERTICAL;
		gbc.insets = new Insets(200, 0, 20, 0);
		spPanel.add(spacer9, gbc);
		final JPanel spacer10 = new JPanel();
		gbc = new GridBagConstraints();
		gbc.gridx = 2;
		gbc.gridy = 7;
		gbc.fill = GridBagConstraints.HORIZONTAL;
		gbc.insets = new Insets(0, 20, 0, 20);
		spPanel.add(spacer10, gbc);
		final JPanel spacer11 = new JPanel();
		gbc = new GridBagConstraints();
		gbc.gridx = 0;
		gbc.gridy = 7;
		gbc.fill = GridBagConstraints.HORIZONTAL;
		gbc.insets = new Insets(0, 20, 0, 0);
		spPanel.add(spacer11, gbc);
		final JPanel spacer12 = new JPanel();
		gbc = new GridBagConstraints();
		gbc.gridx = 4;
		gbc.gridy = 7;
		gbc.fill = GridBagConstraints.HORIZONTAL;
		gbc.insets = new Insets(0, 0, 0, 20);
		spPanel.add(spacer12, gbc);
		messageLabel = new JLabel();
		messageLabel.setText("Please enter following package information");
		gbc = new GridBagConstraints();
		gbc.gridx = 1;
		gbc.gridy = 3;
		gbc.gridwidth = 3;
		gbc.anchor = GridBagConstraints.WEST;
		spPanel.add(messageLabel, gbc);
		final JPanel spacer13 = new JPanel();
		gbc = new GridBagConstraints();
		gbc.gridx = 1;
		gbc.gridy = 2;
		gbc.gridwidth = 3;
		gbc.fill = GridBagConstraints.VERTICAL;
		gbc.insets = new Insets(15, 0, 15, 0);
		spPanel.add(spacer13, gbc);
		final JPanel spacer14 = new JPanel();
		gbc = new GridBagConstraints();
		gbc.gridx = 1;
		gbc.gridy = 0;
		gbc.gridwidth = 3;
		gbc.fill = GridBagConstraints.VERTICAL;
		gbc.insets = new Insets(20, 0, 0, 0);
		spPanel.add(spacer14, gbc);
		printButton = new JButton();
		printButton.setText("Print Shipping Label");
		gbc = new GridBagConstraints();
		gbc.gridx = 3;
		gbc.gridy = 11;
		gbc.anchor = GridBagConstraints.EAST;
		spPanel.add(printButton, gbc);
		final JPanel spacer15 = new JPanel();
		gbc = new GridBagConstraints();
		gbc.gridx = 1;
		gbc.gridy = 12;
		gbc.gridwidth = 3;
		gbc.fill = GridBagConstraints.VERTICAL;
		gbc.insets = new Insets(20, 0, 20, 0);
		spPanel.add(spacer15, gbc);
		yourAccountPanel = new JPanel();
		yourAccountPanel.setLayout(new CardLayout(0, 0));
		cardPanel.add(yourAccountPanel, "yourAccountCard");
		yaPanel = new JPanel();
		yaPanel.setLayout(new GridBagLayout());
		yourAccountPanel.add(yaPanel, "yourAccountCard");
		yaTitleLabel = new JLabel();
		yaTitleLabel.setText("YOUR ACCOUNT INFORMATION");
		gbc = new GridBagConstraints();
		gbc.gridx = 0;
		gbc.gridy = 1;
		gbc.gridwidth = 2;
		gbc.anchor = GridBagConstraints.WEST;
		yaPanel.add(yaTitleLabel, gbc);
		final JPanel spacer16 = new JPanel();
		gbc = new GridBagConstraints();
		gbc.gridx = 0;
		gbc.gridy = 2;
		gbc.fill = GridBagConstraints.VERTICAL;
		yaPanel.add(spacer16, gbc);
		firstNLabel = new JLabel();
		firstNLabel.setText("First Name:");
		gbc = new GridBagConstraints();
		gbc.gridx = 0;
		gbc.gridy = 3;
		gbc.anchor = GridBagConstraints.WEST;
		gbc.insets = new Insets(0, 0, 0, 100);
		yaPanel.add(firstNLabel, gbc);
		final JPanel spacer17 = new JPanel();
		gbc = new GridBagConstraints();
		gbc.gridx = 0;
		gbc.gridy = 4;
		gbc.fill = GridBagConstraints.VERTICAL;
		yaPanel.add(spacer17, gbc);
		lastNLabel = new JLabel();
		lastNLabel.setText("Last Name:");
		gbc = new GridBagConstraints();
		gbc.gridx = 0;
		gbc.gridy = 5;
		gbc.anchor = GridBagConstraints.WEST;
		yaPanel.add(lastNLabel, gbc);
		final JPanel spacer18 = new JPanel();
		gbc = new GridBagConstraints();
		gbc.gridx = 0;
		gbc.gridy = 6;
		gbc.fill = GridBagConstraints.VERTICAL;
		yaPanel.add(spacer18, gbc);
		phoneLabel = new JLabel();
		phoneLabel.setText("Phone Number:");
		gbc = new GridBagConstraints();
		gbc.gridx = 0;
		gbc.gridy = 7;
		gbc.anchor = GridBagConstraints.WEST;
		yaPanel.add(phoneLabel, gbc);
		final JPanel spacer19 = new JPanel();
		gbc = new GridBagConstraints();
		gbc.gridx = 0;
		gbc.gridy = 8;
		gbc.fill = GridBagConstraints.VERTICAL;
		yaPanel.add(spacer19, gbc);
		emailLabel = new JLabel();
		emailLabel.setText("Email:");
		gbc = new GridBagConstraints();
		gbc.gridx = 0;
		gbc.gridy = 9;
		gbc.anchor = GridBagConstraints.WEST;
		yaPanel.add(emailLabel, gbc);
		fLabel = new JLabel();
		fLabel.setText("Label");
		gbc = new GridBagConstraints();
		gbc.gridx = 1;
		gbc.gridy = 3;
		gbc.anchor = GridBagConstraints.WEST;
		gbc.ipadx = 150;
		yaPanel.add(fLabel, gbc);
		lLabel = new JLabel();
		lLabel.setText("Label");
		gbc = new GridBagConstraints();
		gbc.gridx = 1;
		gbc.gridy = 5;
		gbc.anchor = GridBagConstraints.WEST;
		gbc.ipadx = 150;
		yaPanel.add(lLabel, gbc);
		pLabel = new JLabel();
		pLabel.setText("Label");
		gbc = new GridBagConstraints();
		gbc.gridx = 1;
		gbc.gridy = 7;
		gbc.anchor = GridBagConstraints.WEST;
		gbc.ipadx = 150;
		yaPanel.add(pLabel, gbc);
		eLabel = new JLabel();
		eLabel.setText("Label");
		gbc = new GridBagConstraints();
		gbc.gridx = 1;
		gbc.gridy = 9;
		gbc.anchor = GridBagConstraints.WEST;
		gbc.ipadx = 150;
		yaPanel.add(eLabel, gbc);
		final JPanel spacer20 = new JPanel();
		gbc = new GridBagConstraints();
		gbc.gridx = 0;
		gbc.gridy = 10;
		gbc.fill = GridBagConstraints.VERTICAL;
		yaPanel.add(spacer20, gbc);
		addressLabel = new JLabel();
		addressLabel.setText("Address:");
		gbc = new GridBagConstraints();
		gbc.gridx = 0;
		gbc.gridy = 11;
		gbc.anchor = GridBagConstraints.WEST;
		yaPanel.add(addressLabel, gbc);
		aLabel = new JLabel();
		aLabel.setText("Label");
		gbc = new GridBagConstraints();
		gbc.gridx = 1;
		gbc.gridy = 11;
		gbc.anchor = GridBagConstraints.WEST;
		gbc.ipadx = 150;
		yaPanel.add(aLabel, gbc);
		final JPanel spacer21 = new JPanel();
		gbc = new GridBagConstraints();
		gbc.gridx = 0;
		gbc.gridy = 12;
		gbc.fill = GridBagConstraints.VERTICAL;
		yaPanel.add(spacer21, gbc);
		final JPanel spacer22 = new JPanel();
		gbc = new GridBagConstraints();
		gbc.gridx = 0;
		gbc.gridy = 0;
		gbc.fill = GridBagConstraints.VERTICAL;
		yaPanel.add(spacer22, gbc);
	}

	/**
	 * @noinspection ALL
	 */
	public JComponent $$$getRootComponent$$$() {
		return parentPanel;
	}

}
